spring:
  application:
    name: chat-server

  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092

    topic:
      channel-chat-event: "channelChatEvent"
      dm-chat-event: "dmChatEvent"
      connection-event: "connectionEvent"
      presence-event: "presenceEvent"
      notification-event: "notificationEvent"
      server-event: "serverEvent"
      channel-event: "channelEvent"

    producer:
      bootstrap-servers: localhost:9092

    consumer:
      group-id:
        channel-chat-event: "channelChatEventGroup"
        dm-chat-event: "dmChatEventGroup"
        notification-event: "notificationEventGroup"
        server-event: "serverEventGroup"
        channel-event: "channelEventGroup"

      enable-auto-commit: true
      auto-offset-reset: latest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}


snowflake:
  worker-id: ${snowflake.worker-id:${random.value}}
