const SIGNALING_SERVER_URL = import.meta.env.SIGNALING_SERVER_URL

const CHAT_SERVER_URL = import.meta.env.CHAT_SERVER_URL
const SOCKET_URL = import.meta.env.SOCKET_URL

export { CHAT_SERVER_URL, SIGNALING_SERVER_URL, SOCKET_URL }
