const SERVER_URL = import.meta.env.VITE_SERVER_URL
const SIGNALING_SERVER_URL = import.meta.env.VITE_SIGNALING_SERVER_URL
const CHAT_SERVER_URL = import.meta.env.VITE_CHAT_SERVER_URL
const SENTRY_DSN = import.meta.env.VITE_SENTRY_DSN
const MOCK_SERVICE_WORKER = import.meta.env.VITE_MOCK_SERVICE_WORKER === 'true'
const TURN_SERVER_URL = import.meta.env.VITE_TURN_SERVER_URL
const SIGNALING_NODE_SERVER_URL = import.meta.env.VITE_SIGNALING_NODE_SERVER_URL
const FILE_SERVER_URL = import.meta.env.VITE_FILE_SERVER_URL

export {
  CHAT_SERVER_URL,
  FILE_SERVER_URL,
  MOCK_SERVICE_WORKER,
  SENTRY_DSN,
  SERVER_URL,
  SIGNALING_NODE_SERVER_URL,
  SIGNALING_SERVER_URL,
  TURN_SERVER_URL
}
