server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: apigateway-server
  main:
    web-application-type: reactive # WebFlux + Spring Web 함께 사용

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 모든 요청에 대해 CORS 적용, TODO: 이후 변경
            allowedOrigins:
              - "http://localhost:5173"
              - "https://dev-fe.d2q3qyb0bos3b9.amplifyapp.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true # serviceId를 소문자로 관리

      routes:
        # Auth Server 라우팅
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - name: PassportFilter

        - id: auth-server-public
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/login,/auth-server/register,/auth-server/health-check

        # User Server 라우팅
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user-server/**
          filters:
            - name: PassportFilter

        # Service Server 라우팅
        - id: service-server
          uri: lb://service-server
          predicates:
            - Path=/service-server/**
          filters:
            - name: PassportFilter

        # Search Server 라우팅
        - id: search-server
          uri: lb://search-server
          predicates:
            - Path=/search-server/**
          filters:
            - name: PassportFilter

        # 상태관리 서버(State Management Server)
        - id: state-server
          uri: lb://state-server
          predicates:
            - Path=/state-server/**
          filters:
            - name: PassportFilter

        # 채팅 서버(Chat Server)
        - id: chat-server
          uri: lb://chat-server
          predicates:
            - Path=/chat-server/**
          filters:
            - name: PassportFilter

        # 채팅 서버 소켓(Chat Server Socket)
        - id: chat-server-socket
          uri: lb://chat-server
          predicates:
            - Path=/ws-chat/**

        # 푸시 서버(Push Server)
        - id: push-server
          uri: lb://push-server
          predicates:
            - Path=/push-server/**
          filters:
            - name: PassportFilter

        # 시그널링 서버(Signaling Server)
        - id: signaling-server
          uri: lb://signaling-server
          predicates:
            - Path=/signal-server/**

        # 미디어 서버(Kurento Server)
        - id: kurento-server
          uri: lb://kurento-server
          predicates:
            - Path=/kurento-server/**

eas:
  passport:
    secret: ${PASSPORT_SECRET_KEY}
    expiration: ${PASSPORT_EXPIRATION}
    header: ${PASSPORT_HEADER}
    algorithm: ${PASSPORT_ALGORITHM}

passport:
  server:
    url: ${PASSPORT_SERVER_URL}