services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: bbebig
      POSTGRES_PASSWORD: bbebig
      POSTGRES_DB: bbebig_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bbebig-network
      
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bbebig
      MONGO_INITDB_ROOT_PASSWORD: bbebig1234
    volumes:
      - mongodb_data:/data/db
    networks:
      - bbebig-network
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - bbebig-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    networks:
      - bbebig-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bbebig  # MySQL 루트 비밀번호 설정
    volumes:
      - mysql_data:/var/lib/mysql
    

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  mysql_data:

networks:
  bbebig-network:
    external: true
