services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbebig-app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    command: ['yarn', 'start']
    volumes:
      - .:/app
      - /app/node_modules
