module.exports = {
    plugins: ['prettier-plugin-tailwindcss'],
    arrowParens: "always",
    bracketSameLine: true,
    bracketSpacing: true,
    endOfLine: "lf",
    printWidth: 100,
    semi: true,
    singleAttributePerLine: true,
    singleQuote: true,
    jsxSingleQuote: true,
    tabWidth: 2,
    trailingComma: "es5",
    useTabs: false,
};