services:
  auth-server:
    build: .
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - ./.env.production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - redis
    restart: always
    networks:
      - auth-network

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ${REDIS_VOLUME}:/data
    command: redis-server --appendonly yes
    networks:
      - auth-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  auth-network:
    driver: bridge

volumes:
  auth-redis-data:
    name: ${REDIS_VOLUME}
