name: Build and Push State Server Image

on:
  push:
    branches:
      - dev/discovery-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SERVER_NAME: discovery-server   # 필요한 경우 바꿔주세요

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gradle
        run: |
          cd src/backend/${{ env.SERVER_NAME }}
          ./gradlew clean build -x test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest \
            ./src/backend/${{ env.SERVER_NAME }}
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest