name: Push Server Image

on:
  push:
    branches:
      - dev/apigateway-server   # 서버 별로 변경 필요
  pull_request:
    branches:
      - dev/apigateway-server   # 서버 별로 변경 필요

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENV_FILE: ${{ secrets.APIGATEWAY_ENV }} # 서버 별로 추가/삭제 필요
      SERVER_NAME: apigateway-server   # 서버 별로 변경 필요

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Inject ENV_FILE
        run: echo "${{ env.ENV_FILE }}" > src/backend/${{ env.SERVER_NAME }}/src/main/resources/.env   # 서버 별로 변경 필요

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd src/backend
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest -f ${{ env.SERVER_NAME }}/Dockerfile .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest