name: Push Server Image

on:
  push:
    branches:
      - dev/auth-server   # 서버 별로 변경 필요
  pull_request:
    branches:
      - dev/auth-server   # 서버 별로 변경 필요

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ENV_FILE: ${{ secrets.ENV_FILE }}
      SERVER_NAME: auth-server  # 서버 별로 변경 필요
    
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Inject ENV_FILE
        run: echo "${{ env.ENV_FILE }}" > src/backend/auth-server/.env.production

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd src/backend/${{ env.SERVER_NAME }}
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVER_NAME }}:latest
