name: Lint Check

on:
  pull_request:
    branches: [dev/fe]
  push:
    branches: [dev/fe]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "./src/frontend/yarn.lock"

      - name: Install Dependencies
        working-directory: ./src/frontend
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./src/frontend
        run: yarn lint --max-warnings=0

      - name: Check Types
        working-directory: ./src/frontend
        run: yarn check

      - name: Check Format
        working-directory: ./src/frontend
        run: yarn format
