name: Frontend Lint Check

on:
  pull_request:
    branches: [dev/fe]
    paths:
      - "src/frontend/**"
  push:
    branches: [dev/fe]
    paths:
      - "src/frontend/**"

jobs:
  lint:
    if: contains(github.event.head_commit.modified, 'src/frontend/') ||
      contains(github.event.head_commit.added, 'src/frontend/') ||
      contains(github.event.head_commit.removed, 'src/frontend/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "./src/frontend/yarn.lock"

      - name: Install Dependencies
        working-directory: ./src/frontend
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        working-directory: ./src/frontend
        run: yarn lint:fix

      - name: Run Type Check
        working-directory: ./src/frontend
        run: yarn typecheck

      - name: Run Prettier Check
        working-directory: ./src/frontend
        run: yarn format
